services:
  postgres:
    image: postgres:16-alpine
    container_name: agrosmart-db
    environment:
      POSTGRES_DB: agrosmart_db
      POSTGRES_USER: agrosmart_user
      POSTGRES_PASSWORD: agrosmart_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: