server:
  port: 8194

spring:
  application:
    name: agrosmart-comercializacion
  datasource:
    url: jdbc:postgresql://localhost:5432/agrosmart_db
    username: agrosmart_user
    password: agrosmart_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

agrosmart:
  semilla:
    tabla-base: tbl_productos_base_94
    categoria: Banano